spring.application.name=Spring-Security-Proj02-PasswordEncrypt-USING-MYSQLdb

server.port=9090

server.servlet.context-path=/mysqlreg_login

spring.datasource.url=jdbc:mysql://localhost:3306/spring_security_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Kuku@0504


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
